Hynek
=====

NOTE: I want to see you choosing work from this plan and doing English every day. I would like to see you improving your English by trying hard every day and not only when I push you hard. If you think of work you can do, and it is good work, I will probably let you do it, but then you must work on it, and finish it. If you do not work, and do not think of work you can do, I will give you long, horrible dictations just so I know you are working in English.

== Sometime ==

IMPORTANT: I have given you some more interesting projects to work on because I think you are intelligent and responsible enough. If you do not do them, I will give you lots of grammar work to work on on your own.

NOTE: I was hoping to send out the following to parents last week. You worked on it for three minutes and then quit. If you really do not want to do it I will give it to somebody else, but I don't think you tried and I think that if you had tried, you would have enjoyed it. Try it again and then let me know if you want to carry on doing it.

* [ ] Wiki: What Has Blue Class Been Doing

* [ ] Buster Keaton's The Boat. (With another third year other than Eliška.)

* [ ] Class diary

* [ ] Story prompts

== Tuesday ==

* [ ] The First Part of the First Great Lesson

== Thursday ==


== Friday ==
